#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jul  8 11:58:18 2022

@author: ali
"""



import dcor
import math

import numpy as np
from timeit import timeit
import matplotlib.pyplot as plt
from numpy import random
import time

k=1
delta=0.05
V=[]
#np.append(V, V)
#V.append(V)
#V


V=np.arange(0, x.shape[2], 1, dtype=int)

V_temp=V
V_dim=V_temp.shape
V_dim,=V_dim
x_reduced=x

dcors=[]
V_temp_all = []
k=0
V_temp_all = []
c_all=[]
V_temp_all.append(V)
print('Begin iterating process of D-correlation')
while V_dim > 1:
    time1= time.time()
    c=[]
    V_index=[]
    for u in V_temp:
        xtemp=x[:,V_temp,:]
        #print(xtemp.shape)
        xtemp=xtemp[:,:,u]
        #print(xtemp)
        #print(dcor.distance_correlation(xtemp, y))
        c=np.append(c,dcor.distance_correlation(xtemp, y))
       # c=np.append(c,dcor.partial_distance_correlation(xtemp, y,y3)) #partial distance correlation

        #print(c)
    #print(np.max(c))
    dcors.append(np.max(c))
    t_temp=np.quantile(c,delta) 
    index_temp=c>t_temp
    
    #print(index_temp)
    #x_reduced=x_reduced[:,index_temp,:]
    #x_reduced=x_reduced[:,:, index_temp]

    #print(dcor.distance_correlation(x_reduced, y))
    #V_temp=np.arange(0, x_reduced.shape[1], 1, dtype=int)
    #V_temp=[i for i,x in enumerate(index_temp) if x]
    V_temp = np.array(V_temp_all[k])[index_temp]
    V_temp_all.append(V_temp)
    c_all.append(c)
    #V_temp=V_temp[index_temp] 
    #x.shape[2]            
    V_dim=np.size(V_temp)
    time_step = time.time() - time1
    print(f'Step {k} accomplished in {time_step} secs, max time {x.shape[1]*time_step*(1-delta)**k}')
    k=k+1
    

    
    
index_winner=np.max(np.argwhere(dcors == np.amax(dcors)))
    
print(dcors[index_winner])
print(V_temp_all[index_winner].shape)

V_winner=V_temp_all[index_winner]
c_winner=c_all[index_winner]

import pandas
atlas=pandas.read_csv('/Users/ali/Desktop/Jul/apoe/mouse_anatomy.csv')
#noreadcsf=[148,152,161,314,318,327]
# remove white matter too:
noreadcsf=[ 148, 152, 161, 314, 318, 327, 120, 121, 122, 134, 102, 118, 119, 123, 124, 125, 126,
127, 128, 129, 130, 131, 132, 133, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144,
145, 146, 147, 150, 268, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295,
296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312,
313, 316]


noreadcsf=[x - 1 for x in noreadcsf]



atlas=atlas.drop(atlas.index[noreadcsf])

report=atlas.iloc[V_winner]
report['score']=c_winner
report=report.sort_values('score', ascending=False)

print(report)


import matplotlib.pyplot as plt
dimensions=[x.shape[0]for x in V_temp_all]
plt.scatter( dimensions[0:len(dimensions)-1] , dcors )
plt.show()
